apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: himateja0206/flaskdemo:latest
        name: flaskdemo
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flaskdemo-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: flaskdemo
