name: CICD Pipeline

on:
  push:
    branches: main

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Install Python 3.9 (Ubuntu example)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.9 python3.9-venv python3.9-distutils
            
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: himateja0206/flaskdemo:latest
          context: .
          file: app/Dockerfile

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set KUBECONFIG
        run: |
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Deploy to k8s
        run: |
          kubectl cluster-info
          kubectl apply -f deployment.yaml
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
